# Numpy_Assignment_2::

## Question:1

### Convert a 1D array to a 2D array with 2 rows?

#### Desired output::

array([[0, 1, 2, 3, 4],
        [5, 6, 7, 8, 9]])

In [1]:
import numpy as np
a = np.arange(0,10)
print(a)
newarray = a.reshape(2,5)
print(newarray)



[0 1 2 3 4 5 6 7 8 9]
[[0 1 2 3 4]
 [5 6 7 8 9]]


## Question:2

###  How to stack two arrays vertically?

#### Desired Output::

In [3]:
x = np.array([[0, 1, 2, 3, 4],
        [5, 6, 7, 8, 9],
       [1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1]])
np.vstack(x)



array([[0, 1, 2, 3, 4],
       [5, 6, 7, 8, 9],
       [1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1]])

## Question:3

### How to stack two arrays horizontally?

#### Desired Output::

In [4]:
x = np.array([[0, 1, 2, 3, 4, 1, 1, 1, 1, 1],
       [5, 6, 7, 8, 9, 1, 1, 1, 1, 1]])

np.hstack(x)



array([0, 1, 2, 3, 4, 1, 1, 1, 1, 1, 5, 6, 7, 8, 9, 1, 1, 1, 1, 1])

## Question:4

### How to convert an array of arrays into a flat 1d array?

#### Desired Output::

In [8]:
x = np.array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])
print(x)
np.ndarray.flatten(x)

[0 1 2 3 4 5 6 7 8 9]


array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

## Question:5

### How to Convert higher dimension into one dimension?

#### Desired Output::

## Question:6

### Convert one dimension to higher dimension?

#### Desired Output::

In [16]:
x = np.array([[ 0, 1, 2],
[ 3, 4, 5],
[ 6, 7, 8],
[ 9, 10, 11],
[12, 13, 14]])
print(x)
newarray = x.reshape(5,3)
print(newarray)

[[ 0  1  2]
 [ 3  4  5]
 [ 6  7  8]
 [ 9 10 11]
 [12 13 14]]
[[ 0  1  2]
 [ 3  4  5]
 [ 6  7  8]
 [ 9 10 11]
 [12 13 14]]


## Question:7

### Create 5x5 an array and find the square of an array?

In [33]:
x = np.random.rand(5,5)*10
print(x)
np.sqrt(x)



[[5.72809387 3.93004827 6.08776591 4.91490178 3.68032199]
 [5.59548481 8.13183548 3.18830127 7.66209587 1.04831822]
 [8.70923877 8.4299838  6.74073694 0.15455112 7.57716234]
 [7.24147233 6.9477533  7.98252655 8.73900005 8.01370967]
 [3.57140588 3.50985161 6.75707154 6.42900668 2.73451031]]


array([[2.39334366, 1.98243493, 2.46733984, 2.21695778, 1.91841653],
       [2.36547771, 2.85163733, 1.78558149, 2.76804911, 1.02387413],
       [2.95114194, 2.90344344, 2.59629292, 0.3931299 , 2.75266459],
       [2.69099839, 2.63585912, 2.82533654, 2.95617998, 2.83084964],
       [1.88981636, 1.8734598 , 2.59943677, 2.5355486 , 1.65363548]])

## Question:8

### Create 5x6 an array and find the mean?

In [34]:
x = np.random.rand(5,6)
print(x)
np.mean(x)

[[0.55171632 0.4363816  0.2781805  0.50572126 0.83917794 0.30029066]
 [0.56021207 0.0375734  0.31872063 0.39540905 0.74643123 0.82518519]
 [0.68348577 0.70828703 0.59384626 0.83214691 0.04465825 0.72295071]
 [0.26794355 0.62324733 0.54676525 0.00775081 0.42349994 0.52615416]
 [0.46787869 0.78580062 0.47930082 0.96253429 0.42753867 0.56536605]]


0.5154718321010529

## Question:9

### Find the standard deviation of the previous array in Q8?

In [35]:
np.std(x)

0.2388402753913857

## Question:10

### Find the median of the previous array in Q8?

In [36]:
np.median(x)

0.5364597072810089

## Question:11

### Find the transpose of the previous array in Q8?

In [38]:
x.T

array([[0.55171632, 0.56021207, 0.68348577, 0.26794355, 0.46787869],
       [0.4363816 , 0.0375734 , 0.70828703, 0.62324733, 0.78580062],
       [0.2781805 , 0.31872063, 0.59384626, 0.54676525, 0.47930082],
       [0.50572126, 0.39540905, 0.83214691, 0.00775081, 0.96253429],
       [0.83917794, 0.74643123, 0.04465825, 0.42349994, 0.42753867],
       [0.30029066, 0.82518519, 0.72295071, 0.52615416, 0.56536605]])

## Question:12

### Create a 4x4 an array and find the sum of diagonal elements?

In [44]:
x = np.random.rand(4,4)
print(x)
np.trace(x)





[[0.00993494 0.42273401 0.18930819 0.59464805]
 [0.22715858 0.17623626 0.14356664 0.47445856]
 [0.45800794 0.84910192 0.60162424 0.51727184]
 [0.86082646 0.57983099 0.81679323 0.02247935]]


0.8102747871892745

## Question:13

### Find the determinant of the previous array in Q12?

In [46]:
x = np.random.rand(4,4)
print(x)
result =  np.linalg.det(x)
print(result)

[[0.46209723 0.11449073 0.00561003 0.23012512]
 [0.3887849  0.68792925 0.32064863 0.5182856 ]
 [0.16641681 0.95126961 0.67926986 0.64372719]
 [0.5062754  0.87693407 0.35761889 0.82035045]]
0.008983823136105228


## Question:14

### Find the 5th and 95th percentile of an array?

In [54]:
x = np.array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])
print(x)
np.percentile(x,5)
np.percentile(x,95)



[0 1 2 3 4 5 6 7 8 9]


8.549999999999999

## Question:15

### How to find if a given array has any null values?

In [58]:
x = np.array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])
np.isnan(x)

array([False, False, False, False, False, False, False, False, False,
       False])